image: trion/ng-cli-karma

stages:
  - deploy

cache:
  key: "29052020"
  paths:
    - node_modules/

# deploy_master:
#   stage: deploy
#   environment: Production
#   only:
#     - stage

#   script:
#     - node -v
#     - rm ./package-lock.json
#     - npm install -g serverless
#     - npm install
#     - sls config credentials --profile tis-dev --provider aws --key $AWS_KEY --secret $AWS_SECRET
#     - NODE_ENV=dev sls deploy --stage dev --aws-profile tis-dev --config serverless.prod.yml
#     - echo 'Success'

deploy_master:
  stage: deploy
  only:
    - master

  script:
    - node -v
    - rm ./package-lock.json
    - npm install -g serverless
    - npm install
    - sls config credentials --profile servicemind-production --provider aws --key $MASTER_AWS_KEY --secret $MASTER_AWS_SECRET
    - sls prune -n 3
    - NODE_ENV=production sls deploy --stage production --aws-profile servicemind-production --config serverless.prod.yml
    - echo 'Success'



deploy_stage:
  stage: deploy
  only:
    - stage

  script:
    - node -v
    - rm ./package-lock.json
    - npm install -g serverless
    - npm install
    - sls config credentials --profile servicemind-stage --provider aws --key ${STAGE_AWS_KEY} --secret ${STAGE_AWS_SECRET}
    - sls prune -n 3
    - SLS_DEBUG=* NODE_ENV=stage sls deploy --stage stage --aws-profile servicemind-stage --config serverless.stage.yml
    - echo 'Success'
