image: trion/ng-cli-karma:12.1.1

stages:
  - deploy
  - migrate

cache:
  key: "11082021"
  paths:
    - node_modules/


deploy_master:
  stage: deploy
  only:
    - master
  script:
    - node -v
    - rm ./package-lock.json
    - npm install -g serverless
    - npm install
    - sls config credentials --profile pg888-production --provider aws --key $MASTER_AWS_KEY --secret $MASTER_AWS_SECRET
    - NODE_ENV=production sls deploy --stage production --aws-profile pg888-production --config serverless.prod.yml
    - echo 'Success'



migrate_master:
  image: curlimages/curl:7.77.0
  stage: migrate
  only:
    - master
  needs: [
    deploy_master
  ]  
  script:
    - curl -V
    - curl -v https://5dec4xg2n8.execute-api.ap-southeast-1.amazonaws.com/production/db-migration/migrate-latest
    - echo 'Success'
