
service:
  name: ${self:custom.serviceName}

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-s3-local
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  memorySize: 1024
  timeout: 5
  environment:


custom:
  serviceName: tis-serverless-backend
  stage: ${opt:stage, self:custom.defaultStage}
  bucket: dynamic-image-resizing
  defaultStage: dev
  stages:
    - ${opt:stage}
    - dev
    - production
  apigwBinary:
    types:
      - "*/*"


functions:
  app:
    handler: src/app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
