version: '3.5'

services:

    tis-postgresql-server:
        build:
            context: ./postgresql
            args:
                - POSTGRES_USER=servicemind
                - POSTGRES_PASSWORD=password
                - POSTGRES_DB=tis_database
        container_name: tis-postgresql-server
        hostname: tis-postgresql-server        
        volumes:
            - ./data/postgresql/:/var/lib/postgresql
        networks:
            - backend
            - frontend    
        expose:
            - '5432'
        ports:
            - "54320:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U servicemind  tis_database"]
            interval: 15s
            timeout: 5s
            retries: 5

    
    tis-redis-store:
        build:
            context: ./redis
        container_name: tis-redis-store    
        hostname: tis-redis-store    
        volumes:
            - ./data/redis:/data
        networks:
            - backend    
        expose:
            - '6379'
        ports:
            - "6379:6379"    


networks:
  frontend:
  backend:            

  