version: '3.5'

services:

    pg888-postgresql-server:
        build:
            context: ./postgresql
            args:
                - POSTGRES_USER=pg888
                - POSTGRES_PASSWORD=password
                - POSTGRES_DB=pg888
        container_name: pg888-postgresql-server
        hostname: pg888-postgresql-server        
        volumes:
            - ./data/postgresql/:/var/lib/postgresql
        networks:
            - backend
            - frontend    
        expose:
            - '5432'
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pg888  pg888"]
            interval: 15s
            timeout: 5s
            retries: 5

    
    pg888-redis-store:
        build:
            context: ./redis
        container_name: pg888-redis-store    
        hostname: pg888-redis-store    
        volumes:
            - ./data/redis:/data
        networks:
            - backend    
        expose:
            - '6379'
        ports:
            - "6379:6379"    


networks:
  frontend:
  backend:            

  